const PluginFileString = "# Autogenerated by fastlane\n#\n# Ensure this file is checked in to source control!\n\ngem 'fastlane-plugin-teams'\ngem 'fastlane-plugin-diawi'";

module.exports = PluginFileString;
