/* eslint-disable operator-linebreak */
const PluginFileString =
  "# Autogenerated by fastlane\n#\n# Ensure this file is checked in to source control!\n\ngem 'fastlane-plugin-teams'\ngem 'fastlane-plugin-diawi'\ngem 'fastlane-plugin-installonair'";

module.exports = PluginFileString;
